### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by zhaocong22** [dalebenjamin/Youmi-Vocabulary#1]
想问一下你的hotapp.js和wilddog-weapp-all.js文件里面放的是什么呀？表示看不懂！！！
qq：987745375

**Comment by Cedarest** [comment]
HotApp是一个统计云后台，它可以给你提供Api接口来进行数据的存储和读取。（例如笔记本功能的实现，就是将用户的数据通过api传输到hotapp后台的）Wilddog那个是之前用来实现聊天通信的，但是当前版本已经停止使用了，所以直接把它删掉就行。我的QQ是910847330
